org: johanpedroo
app: ton
service: ton
frameworkVersion: '2'

plugins:
  - serverless-dynamodb-local
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true
      seed: true
    migration:
      dir: offline/migrations
    seed:
      test:
        sources:
          - table: ${self:provider.environment.DYNAMODB_TABLE}-users
            sources: [./__tests__/seeds/users.json]
provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  memorySize: 256
  environment:
    DYNAMODB_TABLE: ${self:service}-${sls:stage}
  httpApi:
    cors: true
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource: 'arn:aws:dynamodb:${aws:region}:*:table/${self:provider.environment.DYNAMODB_TABLE}*'

package:
  excludeDevDependencies: true
  exclude:
    - '.dynamodb/**'
    - 'dynamodb/**'
    - 'node_modules/aws-sdk/**'
    - '__tests__/**'
    - '__mocks__/**'
    - 'coverage'
    - 'offline'

functions:
  createUser:
    handler: handlers/users/create.createUser
    events:
      - httpApi:
          path: /v1/user
          method: post
  getUser:
    handler: handlers/users/get.getUser
    events:
      - httpApi:
          path: /v1/user/{id}
          method: get
  getvisits:
    handler: handlers/visits/get.getVisits
    events:
      - httpApi:
          path: /v1/visits
          method: get
  registerVisits:
    handler: handlers/visits/register.registerVisit
    events:
      - httpApi:
          path: /v1/visits/hit
          method: get

resources:
  Resources:
    usersTable:
      Type: 'AWS::DynamoDB::Table'
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:provider.environment.DYNAMODB_TABLE}-users
